Patch/2.35/12244
PrimerAI/beam pull request #2
Opened 2022-01-10 23:32 UTC by joseparajelesGL

Patches the one in #1 
Removes the upper cap in typing extensions

2022-01-11 22:21 UTC, olivierlefloch requested changes

2022-01-11 22:21 UTC, olivierlefloch commented on sdks/python/setup.py
> +    'typing-extensions>=3.7.0',
```suggestion
    'typing-extensions>=3.7.0,<5',
```

2022-01-11 22:21 UTC, olivierlefloch commented on sdks/python/setup.py
> +    'httplib2>0.20.0',
```suggestion
    'httplib2>=0.20.0,<0.21.0',
```

2022-03-31 20:20 UTC, deepix commented
@joseparajelesGL Do you want to close this and #1, your commits are captured by the primer-cumulative branch?

2022-09-08 19:23 UTC, closed without merging